services:
  db:
    image: postgres:16
    container_name: auction-db
    environment:
      POSTGRES_DB: auction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: .
    container_name: auction-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/auction_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: auction-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
